loading.enable=true
loading.mode=http
loading.filePath=./currency_rates.txt

scheduler.executionTime=21:39

database.url=jdbc:postgresql://localhost:5432/postgres
database.username=postgres
database.password=admin