loading:
  enable: true
  mode: http
  history-days: 10
  file-path: ./currency_rates.txt
  http:
    url: https://api.nbrb.by/exrates/rates?periodicity=0
    timeout: 10s
    max-attempts: 3

scheduler:
  cron: "0 1 0 * * *"

spring:
  config:
    import: classpath:application-access.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: cur_ex
        format_sql: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    schemas: cur_ex
    create-schemas: true
logging:
  config: classpath:log4j2.properties

app:
  cors:
    allowed-origins: http://localhost:63342,http://localhost:8080
