loading.enable=true
loading.mode=http
loading.filePath=./currency_rates.txt

scheduler.executionTime=21:39

spring.datasource.database.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.database.username=postgres
spring.datasource.database.password=admin